name: Registration Form Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        npm install jest puppeteer jest-puppeteer jest-junit
        npm install -g http-server
        
    - name: Start HTTP server
      run: |
        http-server -p 5500 &
        sleep 5 # Sunucunun başlaması için bekle
        
    - name: Run tests
      run: npm test
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-report.xml